### ISSUE TITLE
Unknown Prop!

### ISSUE THREAD

**Issue by rsflow** [olahol/react-tagsinput#91]
Hi,

The `classNameRemove` prop issues a warning with the new React. 
`Unknown prop 'classNameRemove' on <span> tag. Remove this prop from the element.` 

Thank You!

**Comment by olahol** [comment]
I think this is fixed in version `3.11.0`, have you tried it?

**Comment by rsflow** [comment]
@olahol I have `3.11.0` and it's not fixed ... maybe you fixed it in the `3.12.0`
